Lesson6!
Rityao/LevelUp.CsharpJuniors.Hometasks pull request #10
Opened 2023-02-27 12:12 UTC by Rityao

scripts

2023-03-01 20:19 UTC, avchirkin requested changes

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create Clients.sql
> +	[Phone] [nvarchar](100) NULL,
Какой-то из контактов (или оба) нужно сделать обязательными. Все магазины требуют оставить хоть какую-то контактную информацию

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create OrderDetails.sql
> +	[Price] [decimal](18, 0) NOT NULL,
Точность после запятой нужна. Иначе копейки потеряются. Или использовать тип money

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create OrderStatuses.sql
> + CONSTRAINT [PK_OrderStatuses] PRIMARY KEY CLUSTERED
Здесь индекс не особо нужен. В статусах заказа будет 3-4 статуса, индекс будет неэффективен в такой таблице

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create Prices.sql
> +	[Price] [decimal](18, 0) NOT NULL
Точность после запятой или тип money

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create ShopItems.sql
> +	[Name] [nvarchar](100) NOT NULL,
Для названия товара лучше заложить длину побольше

2023-03-01 20:19 UTC, avchirkin commented on Lesson6/Scripts/Create StockKeepingUnits.sql
> +	[Amount] [int] NOT NULL,
Лучше float

2023-03-03 21:22 UTC, Rityao commented on Lesson6/Scripts/Create Clients.sql
> +	[Phone] [nvarchar](100) NULL,
++

2023-03-03 21:22 UTC, Rityao commented on Lesson6/Scripts/Create OrderDetails.sql
> +	[Price] [decimal](18, 0) NOT NULL,
++

2023-03-03 21:22 UTC, Rityao commented on Lesson6/Scripts/Create Prices.sql
> +	[Price] [decimal](18, 0) NOT NULL
++

2023-03-03 21:22 UTC, Rityao commented on Lesson6/Scripts/Create ShopItems.sql
> +	[Name] [nvarchar](100) NOT NULL,
++

2023-03-03 21:22 UTC, Rityao commented on Lesson6/Scripts/Create StockKeepingUnits.sql
> +	[Amount] [int] NOT NULL,
++

2023-03-08 18:16 UTC, avchirkin approved these changes

2023-03-08 19:03 UTC, merged