Lesson7_2
Rityao/LevelUp.CsharpJuniors.Hometasks pull request #12
Opened 2023-02-28 20:35 UTC by Rityao

2. Create console application which would concatenate the content of all text files from the directory. 
Directory should be passed via console application argument. All text files from that directory should be 
copied in one one and saved in the same directory. Use asynchronous API

2023-03-01 20:47 UTC, avchirkin requested changes

2023-03-01 20:47 UTC, avchirkin commented on Lesson7_2/Program.cs
> +internal class Program : System.IO.IOException
Зачем здесь наследование от исключения?

2023-03-01 20:47 UTC, avchirkin commented on Lesson7_2/Program.cs
> +                string? text = File.ReadAllText(path + fileName);       // предыдущий вариант: string StreamReader sr = File.OpenText(path + "\\" + fi.Name); и sr.ReadLine() читает одну строку
Читать лучше тоже асинхронно

2023-03-01 20:47 UTC, avchirkin commented on Lesson7_2/Program.cs
> +                string? text = File.ReadAllText(path + fileName);       // предыдущий вариант: string StreamReader sr = File.OpenText(path + "\\" + fi.Name); и sr.ReadLine() читает одну строку
path + fileName повторяется в нескольких местах. Можно вынести в переменную

2023-03-01 20:47 UTC, avchirkin commented on Lesson7_2/Program.cs
> +                string? text = File.ReadAllText(path + fileName);       // предыдущий вариант: string StreamReader sr = File.OpenText(path + "\\" + fi.Name); и sr.ReadLine() читает одну строку
Используй Path.Combine для совмещения адреса директории и файла

2023-03-04 11:22 UTC, Rityao commented on Lesson7_2/Program.cs
> +                string? text = File.ReadAllText(path + fileName);       // предыдущий вариант: string StreamReader sr = File.OpenText(path + "\\" + fi.Name); и sr.ReadLine() читает одну строку
++

2023-03-04 11:22 UTC, Rityao commented on Lesson7_2/Program.cs
> +                string? text = File.ReadAllText(path + fileName);       // предыдущий вариант: string StreamReader sr = File.OpenText(path + "\\" + fi.Name); и sr.ReadLine() читает одну строку
++

2023-03-04 11:22 UTC, Rityao commented on Lesson7_2/Program.cs
> +internal class Program : System.IO.IOException
с чем-то спутала.. А в целом наследование от какого-либо исключение нужно если мы захотим в классе этого исключения метод переписать?

2023-03-08 18:23 UTC, avchirkin commented on Lesson7_2/Program.cs
> +                string fiName = Path.Combine(path,fi.Name);
В учебной задаче не очень существенно, но в боевом коде настоятельно рекомендую всегда проверять выполнимость операций и валидировать входные данные. Особенно те, что пришли из консоли. Например, путь к директории может быть введён некорректно - нужно проверять.

2023-03-08 18:26 UTC, avchirkin commented on Lesson7_2/Program.cs
> +                using FileStream fstreamR = new(fiName, FileMode.Open); //экземпляр для чтения из файла
Над неймингом я бы ещё подумал. Не очень прозрачное название, без коммента догадаться было бы непросто, чем эти стримы отличаются

2023-03-08 18:27 UTC, avchirkin commented on Lesson7_2/Program.cs
>                  string textFromFile = Encoding.Default.GetString(buffer);     // декодируем байты в строку
Тут кодировка Default, а выше ты используешь ASCII для записи символа перевода строки. Надо бы определиться

2023-03-08 18:28 UTC, avchirkin requested changes
Несколько небольших замечаний

2023-03-19 18:50 UTC, Rityao commented on Lesson7_2/Program.cs
> +                using FileStream fstreamR = new(fiName, FileMode.Open); //экземпляр для чтения из файла
++

2023-03-19 18:51 UTC, Rityao commented on Lesson7_2/Program.cs
> +                string fiName = Path.Combine(path,fi.Name);
добавила проверку + проверку, что в папке есть файлы

2023-03-19 19:03 UTC, Rityao commented on Lesson7_2/Program.cs
>                  string textFromFile = Encoding.Default.GetString(buffer);     // декодируем байты в строку
написала UTF-8, искала какая же кодировка по дефолту, но похоже она и есть)

2023-04-04 07:02 UTC, avchirkin approved these changes

2023-04-04 10:42 UTC, merged