fix: Lesson3
Rityao/LevelUp.CsharpJuniors.Hometasks pull request #14
Opened 2023-03-03 20:00 UTC by Rityao

IdNumber изменен на id, из интерфейса убран метод, убраны методы из наследников Food

2023-03-08 18:11 UTC, avchirkin requested changes
Абстрактность свойств класса StoreItem - проблема, подробнее - в комментах по коду. Остальное поправлено, молодчина

2023-03-08 18:11 UTC, avchirkin commented on Lesson3/Categories/Subcategories/Protein.cs
> +            Id = 123; // перезапишет IdNumber из Program.cs
А зачем его перезаписывать? Либо генерируем Id на месте, либо получаем через конструктор. А сейчас получится, что мы получаем Id снаружи, сохраняем его в базовый класс, а потом переписываем хардкодом. При этом, код, который создавал этот экземпляр Protein, рассчитывает на то, что у объекта тот Id, что был передан в конструктор

2023-03-08 18:11 UTC, avchirkin commented on Lesson3/Categories/Subcategories/Water.cs
> +            Id = 789;
Тут тоже надо понять, всё же, через конструктор мы хотим Id прокидывать или считать на месте

2023-03-08 18:11 UTC, avchirkin commented on Lesson3/StoreItem.cs
>          public abstract string? Name { get; set; }
Абстрактность этих свойств сомнительна. Абстрактными обычно делают те члены класса, которые "наследник знает, как переопределить правильно для него". Насчёт Name - что тут переопределять? Строка - она и в Африке строка. То же самое касается и других свойств. Все они слишком простые, чтобы у наследников могла возникнуть необходимость в их переопределении. Можно оставить StoreItem абстрактным, чтобы нельзя было создавать его экземпляры, но делать абстрактными все его свойства не нужно

2023-03-08 18:11 UTC, avchirkin commented on Lesson3/Categories/Wear.cs
> +        public override int Id { get; set; }
Смотри замечание в StoreItem. Так как свойства абстрактные, ты вынуждена во всех дочерних классах их оверрайдить. Но по факту этот оверрайд бессмысленный - ты не привносишь никакого специфического поведения, у тебя что абстрактное поле Name в StoreItem строка с геттером и сеттером, что тут, что в других классах

2023-03-19 11:25 UTC, Rityao commented on Lesson3/Categories/Subcategories/Protein.cs
> +            Id = 123; // перезапишет IdNumber из Program.cs
хотела проверить, что будет перезаписываться!) уберу

2023-03-19 11:25 UTC, Rityao commented on Lesson3/Categories/Subcategories/Water.cs
> +            Id = 789;
через конструктор

2023-03-19 12:30 UTC, Rityao commented on Lesson3/StoreItem.cs
>          public abstract string? Name { get; set; }
оставила их неабстрактными

2023-03-19 12:30 UTC, Rityao commented on Lesson3/Categories/Wear.cs
> +        public override int Id { get; set; }
убрала

2023-04-04 07:11 UTC, avchirkin approved these changes

2023-04-04 07:11 UTC, avchirkin commented on Lesson3/Categories/Food.cs
> +            IdNumber = idNumber;
Не, Id было лучше гораздо

2023-04-07 19:34 UTC, merged