Lesson 3!
Rityao/LevelUp.CsharpJuniors.Hometasks pull request #8
Opened 2023-02-27 11:54 UTC by Rityao

Категории теперь абстрактные классы, добавлены модификаторы sealed подкатегориям,
в интерфейс добавлен новый метод, который используется в классе Food и его потомках

2023-03-01 20:11 UTC, avchirkin requested changes

2023-03-01 20:11 UTC, avchirkin commented on Lesson3/Interfaces/IHasShelfLife.cs
>      internal interface IHasShelfLife
Метод HasShelf здесь лишний. Если ты в классе наследуешь интерфейс IHasShelfLife, то это уже означает, что у товара этого класса (и дочерних, разумеется) ЕСТЬ срок годности

2023-03-01 20:11 UTC, avchirkin commented on Lesson3/StoreItem.cs
>          public abstract int IdNumber { get; set; }
Просто Id будет лучше

2023-03-01 20:11 UTC, avchirkin commented on Lesson3/Categories/Subcategories/Water.cs
> +            DateTime today = DateTime.Today;
Логика определения "просрочки" повторяется в разных дочерних классах класса Food. Если в твоём магазине все пищевые продукты имеют срок годности, наследуй интерфейс IHasShelfLife и вынеси эту логику в класс Food. Если не все пищевые товары имеют срок годности, можно создать дочерний класс FoodWithShelfLife, наследовать интерфейс IHasShelfLife в нём и все товары, у которых есть срок годности, наследовать не от Food, а от FoodWithShelfLife. Выбор за тобой

2023-03-03 19:49 UTC, Rityao commented on Lesson3/Categories/Subcategories/Water.cs
> +            DateTime today = DateTime.Today;
Оставлю в Food! Сбило то, что класс абстрактный и казалось, что в абстрактном классе должны быть только абстрактные методы, а тогда в нём не прописать было бы тело.

2023-03-03 19:50 UTC, Rityao commented on Lesson3/StoreItem.cs
>          public abstract int IdNumber { get; set; }
+

2023-03-03 19:51 UTC, merged